export TOPIC_REACT="queue-react"
export TOPIC_GIN="queue-golang"
export TOPIC_EXPRESS="queue-express"
export TOPIC_RAILS="queue-ruby"
export TOPIC_KOTLIN="queue-kotlin"
export TOPIC_DJANGO="queue-python"
