export TOPIC_REACT="frontend-react"
export TOPIC_GO="backend-go"
export TOPIC_EXPRESS="backend-express"
export TOPIC_RAILS="backend-rails"
export TOPIC_KOTLIN="backend-kotlin"
export TOPIC_PYTHON="backend-python"
